### ISSUE TITLE
Error: listen EADDRINUSE :::8083

### ISSUE THREAD

**Issue by sanyaade-iot** [montagejs/minit#82]
Hello everybody,

I followed the quick start on the github eveything went well but I got port in use error for port 8083.

How and where can I change the default port? I went through pages but I could not find the file where to change minit running port from 8083 to a freely available ones. Many thanks!

God blesses!!!

Best regards,
Sanyaade

**Comment by sanyaade-iot** [comment]
Hello Everybody,

Its me again. I found the solution shortly after I posted the above.
Solution: minit --port xxxxx serve &    <---- this did the trick as I found inside the:-  lib/server.js file

Many thanks!

Please close this issue

God blesses!!!

Best regards,
Sanyaade

**Comment by thibaultzanini** [comment]
Hi,

You can just use the -p or —port <number> option.

Thanks,

Thibault Zanini.
